services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'user-and-subscription-app:0.0.1'
    container_name: 'user-and-subscription-app'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://user-and-subscription-db:5432/postgres
    ports:
      - '8088:8088'
    depends_on:
      - 'user-and-subscription-db'
    restart: on-failure

  user-and-subscription-db:
    image: 'postgres:14-alpine'
    container_name: 'user-and-subscription-db'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure