-- name: create tables: users, subscriptions and user_subscriptions
-- author: Renat Mingazov
-- date: 2025.05.10

CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name           VARCHAR(50) NOT NULL,
    created_at          TIMESTAMP NOT NULL
    );

CREATE TABLE IF NOT EXISTS subscriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_name   VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS user_subscriptions (
    user_id             BIGINT REFERENCES users(id),
    subscription_id     BIGINT REFERENCES subscriptions (id),
                        PRIMARY KEY (user_id, subscription_id)
    );